[project]
name = "shared"
version = "0.1.0"
description = "Common shared package"
readme = "README.md"
authors = [
    { name = "Ajay Kanki", email = "222144676+ajaykanki@users.noreply.github.com" }
]
requires-python = ">=3.13"
dependencies = [
    "keyring>=25.7.0",
    "loguru>=0.7.3",
    "pydantic>=2.12.4",
    "pydantic-settings>=2.12.0",
]

[project.scripts]
shared = "shared:main"

[build-system]
requires = ["uv_build>=0.8.2,<0.9.0"]
build-backend = "uv_build"
