[project]
name = "sap-gui-engine"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Ajay Kanki", email = "222144676+ajaykanki@users.noreply.github.com" }
]
requires-python = ">=3.13"
dependencies = [
    "pywinauto>=0.6.9",
]

[project.scripts]
sap-gui-engine = "sap_gui_engine:main"

[build-system]
requires = ["uv_build>=0.8.2,<0.9.0"]
build-backend = "uv_build"
