[project]
name = "app"
version = "0.1.0"
description = "Main application for the automation stack"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "fastapi[standard]>=0.122.0",
    "o365>=2.1.7",
    "scalar-fastapi>=1.4.4",
    "shared",
]

[tool.uv.sources]
shared = { workspace = true }
