[project]
name = "worker"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "fastexcel>=0.18.0",
    "polars>=1.35.2",
    "procrastinate>=3.5.3",
    "psycopg[binary]>=3.2.13",
    "pydantic-settings>=2.12.0",
    "rpatoolkit>=0.1.2",
    "sap-gui-engine",
    "tenacity>=9.1.2",
    "xlsxwriter>=3.2.9",
]

[tool.uv.sources]
sap-gui-engine = { workspace = true }
